# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

 couchdb0:
   container_name: couchdb0
   image: hyperledger/fabric-couchdb:0.4.10
   volumes:
     - ./chainData/couchdb/couchdb0org1:/opt/couchdb/data
   ports:
     - "5984:5984"

 peer0.org1.hf.chainhero.io:
  container_name: peer0.org1.hf.chainhero.io
  extends:
    file:  base/docker-compose-base.yaml
    service: peer0.org1.hf.chainhero.io
  environment:
   - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
   - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
  depends_on:
    - couchdb0
  extra_hosts:
    - "orderer.hf.chainhero.io:39.104.77.237"
    - "orderer1.hf.chainhero.io:114.115.200.251"
    - "peer1.org1.hf.chainhero.io:114.115.200.251"
      
